function VED_RawData = VED_RawData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VED171101 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  VED171101 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VED171101 = importfile("C:\Users\franc\OneDrive - unime.it\General\02_2024_CNR_V2G\V2G_Unime_GUI\Data\VED\RawData\171101\VED171101.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jun-2025 14:55:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Daytime_dd_mm_yyyy_hh_ss", "Daynum_d", "VehId", "Trip", "Timestamp", "Latitude", "Longitude", "HVBatterySoc", "Distance", "Stop_d", "Stop_hh_mm_ss"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Daytime_dd_mm_yyyy_hh_ss", "InputFormat", "dd-MMM-yyyy HH:mm:ss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "Stop_hh_mm_ss", "InputFormat", "HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
VED_RawData = readtable(filename, opts);

end